### PR TITLE
New Bismark summary report script

### PR DESCRIPTION
**Pull request by ewels**
New stand-alone script to generate a summary report of lots of Bismark analyses.

### CODE REVIEW

**Comment by senthil10** [comment]
a PR with `468` lines of `html` code, during my `PR` watch 

image

**Comment by senthil10** [comment]
but where are the files :sweat_smile:

**Comment by ewels** [comment]
Not to mention 1,116 lines of new code overall. My bad.. It _is_ [pretty](https://rawgit.com/ewels/visualizations/master/examples/bismark_summary_report.html) though.. :wink:

**Comment by senthil10** [comment]
@ewels : Indeed, it is pretty :) The contents of bigger files are not shown under `files changed`, were they just renamed ? So can I merge it ?

**Comment by ewels** [comment]
The stuff that isn't shown and has a → symbol were renamed. The main thing is a new script at the bottom (also not shown as it's big) called `stand_alone/bismark_summary/bismark_summary_report.pl`. The other readme changes and examples etc are all to go along with that.

I'm happy for it to be merged without review if people aren't comfortable with Perl. I haven't done quite as much testing as I'd hoped due to milou going down again this afternoon, but I'm pretty confident that it's stable.

**Comment by senthil10** [comment]
Cool, I will leave it open until tomorrow if someone wants to review `638 line of perl code` :sweat_smile: 

P.S: Regarding uppmax, I am only ' ' this close for [last two positions](http://img0.joyreactor.com/pics/post/camasutra-geek-computer-positions-200849.jpeg)

**Comment by ewels** [comment]
Hah, ace!

**Comment by senthil10** [comment]
MERGING :loudspeaker: :loudspeaker:

**Pull request merged**
