### PR TITLE
Made it easier to import and use count_biotypes.

### PR DESCRIPTION
**Pull request by ewels**
Before, you had to do:
```python
from ngi_visualizations import count_biotypes
count_biotypes.count_biotypes.count_biotypes('one', 'two')
```

With the above, it's a little simpler:
```python
#!/usr/bin/env python
from ngi_visualizations import count_biotypes
count_biotypes('one','two')
```

### CODE REVIEW

**Comment by Hammarn** [comment]
Neat!

**Comment by ewels** [comment]
Yeah, except it doesn't work. Don't merge yet.. ;)

**Comment by ewels** [comment]
Ok, so after more testing it's actually more like this:

#### Before
```python
from ngi_visualizations.count_biotypes import count_biotypes
count_biotypes.count_biotypes_main('ann.txt','data.txt')
```

#### After
```python
from ngi_visualizations import count_biotypes
count_biotypes.count_biotypes.count_biotypes_main('ann.txt','data.txt')
```

..did I mention that I hate imports?

**Comment by ewels** [comment]
Ok, I got rid of the fancy import stuff and just renamed things to make it all clearer. Now works with:

```python
#!/usr/bin/env python
from ngi_visualizations.biotypes import count_biotypes
count_biotypes.main('ann.txt', 'data.txt')
```

Can merge now :)

**Comment by Hammarn** [comment]
Comments superfluous

**Comment by chuan-wang** [comment]
Tested and worked well!

**Pull request merged**
